name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.1.0
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    path: ../
  image_picker:
    git: https://github.com/kumsumit/image_picker.git
  photo_viewer:
    git: https://github.com/kumsumit/photo_viewer.git
  video_player: 
    git: https://github.com/kumsumit/video_player.git
  youtube_player_flutter:
    git: https://github.com/sumitsharansatsangi/youtube_player_flutter.git
  saver_gallery: 
    git: https://github.com/kumsumit/saver_gallery.git
  math_keyboard:
    git: https://github.com/kumsumit/math_keyboard.git
  string_validator: ^1.2.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

# The following section is specific to Flutter packages.
flutter:
